# Generated by Django 5.1.1 on 2024-09-18 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('type', models.CharField(choices=[('factory', 'factory'), ('retail', 'retail'), ('sole_trader', 'sole_trader')], max_length=20, verbose_name='Тип')),
                ('is_provider', models.BooleanField(default=False, verbose_name='Признак поставщика')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('country', models.CharField(max_length=150, verbose_name='Страна')),
                ('city', models.CharField(max_length=150, verbose_name='Город')),
                ('street', models.CharField(max_length=150, verbose_name='Улица')),
                ('house', models.CharField(max_length=150, verbose_name='Номер дома')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название товара')),
                ('brand', models.TextField(verbose_name='Модель товара')),
                ('market_entry', models.DateField(verbose_name='Дата выхода на рынок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID накладной')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена за единицу')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
                ('total', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма к оплате')),
                ('is_ship', models.BooleanField(default=False, verbose_name='Признак отгрузки товара')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Признак оплаты товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='trading_network.organization', verbose_name='Поставщик')),
                ('retail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retail', to='trading_network.organization', verbose_name='Розничная сеть')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading_network.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Товарная ведомость',
            },
        ),
    ]
