# Generated by Django 5.1.1 on 2024-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Торговая сеть'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Склад'},
        ),
        migrations.AlterField(
            model_name='consignment',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество товара'),
        ),
    ]
